# Generated by Django 5.0.3 on 2024-04-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialskills',
            options={'verbose_name_plural': 'Habilidades especiales'},
        ),
    ]
